IMAGE_NAME = "bento/ubuntu-20.04"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "gitlab-runner" do |gitlab|
        gitlab.vm.box = IMAGE_NAME
        gitlab.vm.network :private_network, type: "dhcp"
        gitlab.vm.hostname = "gitlab-runner"
     end
end